apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: mongo-service
  namespace: user1-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/jduimovich0/mongo
        name: container-image
        resources: {}
status: {}
